FROM debian:buster

# Add required cross-compiler architectures
RUN dpkg --add-architecture arm64
RUN apt-get update

# Install dependencies and cross compile toolchain
# The dockerfile currently assumes an amd64 build machine.
RUN DEBIAN_FRONTEND=noninteractive apt-get install --yes make git curl pkg-config libpcap-dev libpcap-dev:arm64 libsystemd-dev libsystemd-dev:arm64 gcc-aarch64-linux-gnu gcc gettext-base

# Install the rust toolchain
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > sh.rustup.rs
RUN sh sh.rustup.rs -y

RUN rustup target add aarch64-unknown-linux-gnu

ENV PATH="/usr/local/go/bin:${PATH}"

COPY ./ /haulage
COPY ./pkg/docker-entrypoint.sh /haulage

WORKDIR /haulage

ENTRYPOINT ["/usr/bin/env", "bash", "/haulage/docker-entrypoint.sh", "debian10", "buster"]
